### PR TITLE
Profile page

### PR DESCRIPTION
**Pull request by jrnorth**
Overhauled the profile page UI and made an adjustment to the main page (if the list of sets gets really long, the main content gets pulled down from the top of the page). I can handle the merge for this once we decide to go ahead with it.

### CODE REVIEW

**Comment by ryandougherty** [comment]
What's causing the conflicts?

**Comment by jrnorth** [comment]
I had to add some stuff to index.html for the tabs, which I don't have on this branch.

**Comment by dhganey** [comment]
This looks like this on my machine:

screen shot 2015-04-02 at 21 19 47

On the heroku branch, however, it looks fine:

screen shot 2015-04-02 at 21 20 26

**Comment by jrnorth** [comment]
Strange. It ought to look like this: 
profile

**Comment by jrnorth** [comment]
I changed the layout of the page so there wasn't a bunch of whitespace to the right. I think this looks better, but it's up for discussion.

**Pull request merged**
