### PR TITLE
Set list controls

### PR DESCRIPTION
**Pull request by jrnorth**
I've added controls to the set list browser that allow you to filter by EOR0/EOR1 and low/high. You can also sort by set data hours and set creation time. Finally, I modified the set list browser UI to reduce whitespace.

### CODE REVIEW

**Comment by ryandougherty** [comment]
This looks awesome, I think we are ready to merge.

**Comment by dhganey** [comment]
@jrnorth, code looks great. I did a functional review too and the drop down menus look awesome on my machine, but I don't have a lot of sets right now so it's hard to test them. Do they stack with AND, e.g. you could get just your sets which are EOR0 and are high?

**Comment by jrnorth** [comment]
@dhganey Yes.

**Comment by dhganey** [comment]
Great!

**Pull request merged**
