### PR TITLE
Set view page and comment redo

### PR DESCRIPTION
**Pull request by jrnorth**
Now there's a graph on the set view page and instead of being tied to sets, comments are generalized and organized into threads on the main page.
commentsfinal
setviewpage

### CODE REVIEW

**Comment by dhganey** [comment]
I'm getting an error when I load the page:

Traceback (most recent call last):
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/eorlive_prototype/app/comments.py", line 7, in get_all_comments
    threads = models.Thread.query.all()
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2320, in all
    return list(self)
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2438, in __iter__
    return self._execute_and_instances(context)
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2453, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (ProgrammingError) relation "thread" does not exist
LINE 2: FROM thread
             ^
 'SELECT thread.id AS thread_id, thread.title AS thread_title, thread.username AS thread_username, thread.created_on AS thread_created_on \nFROM thread' {}

**Comment by dhganey** [comment]
This looks great. Reviewed and confirmed it works on my machine.

**Comment by ryandougherty** [comment]
Sweet, this looks awesome (also works on my machine)

**Comment by ryandougherty** [comment]
Are we ready to push to the live site then?

**Comment by jrnorth** [comment]
Yes, I'll push it later this evening.

**Pull request merged**
